# Generated by Django 2.2.20 on 2021-05-19 10:19

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='deadline',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='締切日'),
        ),
    ]
